image:
  repository: pluja/whishper
  tag: v3.1.3@sha256:a54b82c63e79340e2ee0edd5d6d29ab97b26f4367f19757493897e28be5f1d2d
  pullPolicy: Always
gpuImage:
  repository: pluja/whishper
  tag: v3.1.3-gpu@2e4b017fab27a6309825973ee65ff5d89b33f9c33307bcd95335301ed63d7caf
  pullPolicy: Always
translateImage:
  repository: libretranslate/libretranslate
  tag: v1.5.6@sha256:92addfc283191facad5473230f0359a16ea9127bcc3f7cf2da1d9b945a83abe7
  pullPolicy: Always
translateGpuImage:
  repository: libretranslate/libretranslate
  tag: v1.5.6-cuda@sha256:a1676094f458932a878f98ffbb538cbd77179ad911ac140a1f1e997d6dc4b92a
  pullPolicy: Always
  
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8082
        targetPort: 80
        
#securityContext:
#  runAsUser: 0
#  runAsGroup: 0
#  fsGroup: 0
#  readOnlyRootFilesystem: false

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
            PUBLIC_TRANSLATION_API_HOST: ""
            PUBLIC_API_HOST: ${WHISHPER_HOST:-}
            PUBLIC_WHISHPER_PROFILE: cpu
            WHISPER_MODELS_DIR: /app/models
            UPLOAD_DIR: /app/uploads
            CPU_THREADS: 4
          probes:
            liveness:
              enabled: true
              port: 5000
            readiness:
              enabled: true
              port: 5000
            startup:
              enabled: true
              port: 5000
        translate:
          imageSelector: translateImage
          env:
            LT_DISABLE_WEB_UI: True
            LT_UPDATE_MODELS: True
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

persistence:
  uploads:
    enabled: true
    mountPath: /app/uploads
  libretranslate-date:
    enabled: true
    mountPath: /home/libretranslate/.local/share
  libretranslate-cache:
    enabled: true
    mountPath: /home/libretranslate/.local/cache

portal:
  open:
    enabled: true
